### ISSUE TITLE
ignoreRdfType=true doesn't work

### ISSUE THREAD

**Issue by dgarijo** [idafensp/ar2dtool#18]
Tested with http://ontosoft.org/software/ontosoft-v0.99.owl

Conf file:
pathToDot=/usr/local/bin/dot;
pathToTempDir=/tmp;
imageSize=1501;
rankdir=LR;

########
#shapes#
########

#classShape=diamond;
#individualShape=diamond;
#literalShape=box;
#arrowhead=normal;
#arrowtail=normal;
#arrowdir=forward;

########
#colors#
########

classColor=orange;
#individualColor=orange;
#literalColor=blue;
#arrowColor=blue;

#######
#files#
#######

generateGvFile=true;
generateGraphMLFile=true;

#############
#RDF options#
#############

nodeNameMode=localname;
ignoreLiterals=true;
ignoreRdfType=true;
synthesizeObjectProperties=true;

#######
#lists#
#######

#includeOnlyElementList=[<>];

**Comment by idafensp** [comment]
Bug fixed, as includeOnlyElementList was empty, the ignoreLiterals and ignoreRdfType filters were not being applied.
