### ISSUE TITLE
Color of classes is ignored

### ISSUE THREAD

**Issue by dgarijo** [idafensp/ar2dtool#19]
Ontology and configuration file is the same as in Isuue  #18 
I have "classColor=orange;" but everything is depicted in black in the graphml.

**Comment by idafensp** [comment]
Apparently colors are being well detected by the tool, the problem is that Classes are not being properly detected when dealing with ontologies. This issue is related to #8

**Comment by idafensp** [comment]
Color was ignored for classes on GraphML. The color codes were wrong. 

Now it is working, but be aware that it doesn't work as expected when ignoreRdfType=true. A new issue has been opened for that scenario #23
