### ISSUE TITLE
Get base namespace from ontology

### ISSUE THREAD

**Issue by dgarijo** [idafensp/ar2dtool#24]
Ar2tool doesn't know the base namespace of the ontology being designed. However, according to LOV, ontologies should have the following metadata property: 
<http://purl.org/vocab/vann/preferredNamespaceUri>
If the ontology has that property, the base namespace can be changed with its value.

**Comment by idafensp** [comment]
AR2Dtool now assumes "base:" as the default prefix string for the base namespace. If it finds any "vann:preferredNamespacePrefix" it then uses its value as prefix string.
