### ISSUE TITLE
Sometimes blank nodes are depicted

### ISSUE THREAD

**Issue by dgarijo** [idafensp/ar2dtool#26]
Is there a possibility to avoid drawing them?
For example, the file attached
![alojamiento owl](https://cloud.githubusercontent.com/assets/1520666/7932768/f0d1bb04-091a-11e5-8faf-cc649dd95fc5.png)

**Comment by idafensp** [comment]
It seems they are not blank nodes, or at least Jena is not able to detect them.

**Comment by idafensp** [comment]
They are owl restrictions. Now the tool is able to detect and filter them.
