### ISSUE TITLE
No output generated, no error / reason / hint given

### ISSUE THREAD

**Issue by rpietzsch** [idafensp/ar2dtool#48]
Hello, 

not sure if bug or user error (I suppose the later), maybe you can give me a hint how to proceed. 

What I did:

- I cloned this repo (master branch)
- I tried
    - `java -jar bin/ar2dtool.jar -i .schema.ttl -o schemaTax.png -t png -c bin/confTaxonomy.txt` and
    - `java -jar bin/ar2dtool.jar -i .schema.ttl -o schemaER.png -t png -c bin/confER.txt`
- output:
    ```
    log4j:WARN No appenders could be found for logger (com.hp.hpl.jena.util.FileManager).
    log4j:WARN Please initialize the log4j system properly.
    log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
    ****PREFIX MAP****
    http://vocab.eccenca.com/eccmeta/:eccmeta
    [...]
    https://vocab.eccenca.com/semedi/:semedi
    ****END PREFIX MAP****
    ```
- result NO png generated
- dot available at default config location: 
    ```
    $ /usr/local/bin/dot -V
    dot - graphviz version 2.36.0 (20140111.2315)
    ```
- `.schema.ttl` is same as at https://vocab.eccenca.com/semedi/

Thanks in advance. Rene

**Comment by idafensp** [comment]
Hi Rene,

thanks for the feedback. I will try to reproduce the error locally. 

On the meanwhile, could you try to execute it with the "-d" option a the end, so as to get a more verbose log.

Best,

**Comment by rpietzsch** [comment]
Thanks for your reply, yes used `-d`.
But did not saw any error or helpful pointer to what to do next. 
Let me collect the output for you...

**Comment by idafensp** [comment]
Hi Rene,

seems that you are missing the flags in your CLI call:

```
GENERATE_FLAGS: you can specify one or more of the flags below to define which files you want to generate:

-gv/GV: using -gv a DOT source file will be generated as FileToOutputFile.gv. Using -GV will also compile the DOT source code into an image with the format specified in OutputFileType.

-gml: using -gml a GraphML source file will be generated as FileToOutputFile.graphml.
```

Try adding them (GV for example for getting the png file) and let me know if it works. It is working for me locally, producing a 4.7mb figure.

Best,

**Comment by rpietzsch** [comment]
Thanks for pointing me to this, works like a charm!
